language: generic

# Dependency of the minted package
#before_install:
# - sudo apt-get install python-pygments
install:
  - source ./texlive/texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
# Change working directory so including files will work
before_script: cd $TRAVIS_BUILD_DIR/
script:
  # Texliveonfly will download packages automatically
  - texliveonfly qha.tex
  # You can use latexmk to automatically handle bibtex and references (recommended)
  - latexmk -pdf qha.tex
